description: "AGIBOTWORLDCHALLENGE"
target:
  name: agi_bot_challenge
  service: sing
  workspace_name: msra_srobot_azureml

environment:
  registry: SrobotRegistry.azurecr.io
  image: aigbotworld_challenge_training:latest

storage:
  data:
    storage_account_name: msrasrobotazur5594418711
    container_name: msrasrobotvlndata
    mount_dir: /work/data
  pretrained_weights:
    storage_account_name: msrasrobotazur5594418711
    container_name: msrasrobotvlnweights
    mount_dir: /work/weights
  outputs:
    storage_account_name: msrasrobotazur5594418711
    container_name: msrasrobotvlnoutputs
    mount_dir: /work/outputs

code:
  local_dir: $CONFIG_DIR/..

jobs:
  - name: step10_vlm
    sla_tier: Premium
    priority: high
    identity: managed
    submit_args:
      env:
        _AZUREML_SINGULARITY_JOB_UAI: "/subscriptions/e033d461-1923-44a7-872b-78f1d35a86dd/resourcegroups/msra_srobot/providers/Microsoft.ManagedIdentity/userAssignedIdentities/msra_srobot_identity"
    sku: 80G4-A100-NvLink
    command:
    - sudo cp -r /tmp/amlt-code-download/* /work
    - sudo chown -R aiscuser /work/src
    - sudo chown -R aiscuser /opt/conda/envs/ptca
    - cd /work && pip install -e ".[test, aloha, xarm, pusht, dynamixel, smolvla]"
    - wandb login --relogin cdda06bb5a63450bca03e711675bf4744659c597
    - echo "WANDB_API_KEY=cdda06bb5a63450bca03e711675bf4744659c597" >> ~/.bashrc
    - export WANDB_API_KEY=cdda06bb5a63450bca03e711675bf4744659c597
    - echo "test"
    - cd /work && accelerate launch --config_file ds_config.yaml -m lerobot.scripts.train_distribute 
      --policy.path="/work/weights/pi0_pretrained_weights/models--lerobot--pi0/snapshots/8f50aacbe079a026391616cf22453de528f2a873" 
      --dataset.repo_id=/work/data/Manipulation-SimData_LeRobot_all 
      --output_dir=/work/outputs/pi0_lerobot/step10_vlm 
      --policy.repo_id=dummy 
      --policy.train_expert_only=false 
      --policy.chunk_size=10 
      --policy.n_action_steps=10 
      --steps=2000000 
      --wandb.enable=true 
      --wandb.project=pi0_lerobot 
      --wandb.disable_artifact=True 
      --policy.optimizer_lr=1e-4 
      --policy.scheduler_decay_steps=200000 
      --policy.scheduler_decay_lr=1e-5  
      --batch_size=8